### ISSUE TITLE
compatibility with raspberry pi zero w

### ISSUE THREAD

**Issue by krazy350** [uugear/Witty-Pi-2#8]
is witty pi 2 compatible with raspberry pi zero w? I encounter the issue that when i press the button on witty pi 2, raspberry starts to boot and than its turned off. I run rasbian stretch.

Thank you.

**Comment by uugear** [comment]
Yes, Witty Pi 2 is compatible with RPi Zero W.
You may find some hints for troubleshooting this kind of issue [here](http://www.uugear.com/portfolio/is-witty-pi-compatible-with-raspberry-pi-3/).

**Comment by krazy350** [comment]
Works. Thank you.
